import UIKit

struct StringConstants {
    static let kLblContinue: String = "continue"
    static let k: String = ""
    static let kMsgShareARide5: String = "Share a ride\n5€‎"
    static let kLblNo: String = "no"
    static let kMsgTeslaModel3: String =
        "Tesla Model 3. Mercedes C 300 e, MG 5 EV, Hyundai Ioniq 5. Toyota Yaris. Audi Q4 e-tron"
    static let kLbl1Oct900pm: String = "1 Oct, 9:00pm"
    static let kLblIsabell50: String = "Isabell\n5.0"
    static let kMsgAddDebitCredi: String = "Add debit/credit card"
    static let kLblAbout: String = "About"
    static let kMsgWaitMorePay: String = "Wait more, pay less"
    static let kMsgOtakaari24Es: String =
        "Otakaari 24, Espoo                        6.4€\n10 Oct, 6:40pm"
    static let kLblLearnMore: String = "learn more"
    static let kLbl380: String = "+380"
    static let kLbl64: String = "                       6.4€\n"
    static let kMsgYourEcotaxiBa: String = "Your ecoTaxi balance"
    static let kMsgLNtinenTee1: String =
        "Läntinen Tee 1, Helsinki                     7.0€\n12 Oct, 5:10pm"
    static let kMsgByClickingOn2: String = "by clicking on continue you are accepting\nour "
    static let kLblViewOpenChats: String = "view open chats"
    static let kLblMap: String = "Map >"
    static let kLblQuickMessages: String = "Quick messages"
    static let kMsgAddExpensePro: String = "Add expense provider "
    static let kLbl702: String = "                7.0€\n"
    static let kLblUsingEcotaxi: String = "Using ecoTaxi"
    static let kLblPetFriendly: String = "Pet friendly"
    static let kMsgShareYourTrip: String = "Share your trips"
    static let kMsgEtelRanta1252: String = "Eteläranta 125, Helsinki"
    static let kMsgAccountAndDat: String = "Account and data "
    static let kLblChildFriendly: String = "Child friendly"
    static let kMsgForgotToLeave: String =
        "Forgot to leave keys for a parther? Or wanna send a bouquet? Give the thing to the driver and he’ll pass it real quik"
    static let kLblAnnMarie: String = "Ann Marie"
    static let kLblYourLocation: String = "Your location >"
    static let kLblOopera: String = "Oopera"
    static let kLblPromotion: String = "Promotion"
    static let kMsgGetACashback: String = "get a cashback using ecoTaxi card"
    static let kMsgEtelRanta125: String =
        "Eteläranta 125, Helsinki                15€\n1 Oct, 9:00pm"
    static let kMsgWeIncludePet: String =
        "We include pet friendly carrier options. Because we consider pets a part of the family "
    static let kLblMyTrips: String = "My trips "
    static let kMsgWaitMorePayL: String = "Wait more\npay less \n4€‎"
    static let kLblBusiness15: String = "Business \n15€‎"
    static let kMsgWorkAndBusine: String = "Work and business trips"
    static let kMsgAddYourTeamT: String =
        "Add your team to ecoTaxi business\nSet up your team account with EcoTaxi"
    static let kLblConfirmAndPay: String = "Confirm and pay"
    static let kMsgWeMakeAccessi: String =
        "We make accessibility easier for differently abled persons by including detachable ramps."
    static let kMsgLNtinenTee13: String =
        "Läntinen Tee 1, Helsinki                  7.0€\n12 Oct, 5:10pm"
    static let kMsgLNtinenTee12: String = "Läntinen Tee 1, Helsinki                     "
    static let kLblMadeWith: String = "Made with "
    static let kMsgTLNlahdenkat: String = "Töölönlahdenkatu 4, Helsinki      5.9€\n17 Oct, 8:09pm"
    static let kLbl1Min: String = "1\nmin"
    static let kMsgNotHurryingW: String =
        "Not hurrying? Wait for another couple of minutes while driver is taking the order out of a restraurant to deliver and pay less!"
    static let kLblCompany: String = "Company"
    static let kLbl75: String = "            7.5€\n"
    static let kMsgLNtinenTee14: String = "Läntinen Tee 1, Helsinki  "
    static let kLblPayment: String = "Payment"
    static let kMsgSetUpYourTea: String = "Set up your team account with EcoTaxi"
    static let kMsgWeSecureFrom: String =
        "We secure from assault, sexualization and maltreatment from men by hiring more women drivers"
    static let kHttpFail: String = "HTTP request failed"
    static let kLblGetMoving: String = "Get moving!"
    static let kMsgSelectAnOlder: String = "Select an older ride"
    static let kMsgEarnMoneyOnY: String = "Earn money on your shedules"
    static let kLbl70: String = "7.0€\n"
    static let kMsgPaymentAndPri: String = "Payment and pricing"
    static let kMsgAddYourTeamT2: String = "Add your team to ecoTaxi business\n"
    static let kMsgYourDriverHas: String = "Your driver has done a fit evaluation"
    static let kLblDelivery11: String = "Delivery \n11€‎"
    static let kMsgSpecialNeeds7: String = "Special needs\n7€‎"
    static let kMsgVaikeAmerika22: String = "Vaike Amerika 23, Tallinn"
    static let kMsgDonTMindHavi: String =
        "Don’t mind having a part of the way with the person you don’t know? Ecotaxi can automatically find you a companion to have a cheaper ride"
    static let kLblReports: String = "Reports"
    static let kMsgOmgILeftMyU: String = "Omg I left my umberella in \nyour car"
    static let kMsgProtectYourCh: String =
        "Protect your child with a special safety chair and a driver who loves driving children!"
    static let kLbl17Oct809pm: String = "17 Oct, 8:09pm"
    static let kInvalidUrl: String = "Invalid URL"
    static let kMsgWomanDriver7: String = "Woman driver\n7€‎"
    static let kLblWomanTaxi: String = "Woman taxi"
    static let kLblLegal: String = "Legal"
    static let kMsgThankYouWait: String = "Thank you! waiting for you outside"
    static let kMsgHelloItsNice: String = "Hello, Its nice to meet you"
    static let kMsgSetUpWorkPro: String = "Set up work profile"
    static let kLblWorkProfile: String = "Work Profile"
    static let kMsgToyotaPriusPr: String =
        "Toyota Prius Prime, Hyundai Ioniq Plug-In Hybrid, Mini Cooper SE Hardtop 2 Door, Nissan LEAF"
    static let kLblPromotions: String = "Promotions"
    static let kMsgAddAPaymentM: String = "Add a payment method "
    static let kMsgOrderForAnoth: String = "Order for another person"
    static let kLblSupportCases: String = "Support cases "
    static let kMsgWhatIsEcotaxi: String = "What is ecoTaxi balance?"
    static let kLblPaymentMethods: String = "Payment methods"
    static let kLblToday: String = "Today"
    static let kLblArrived: String = "Arrived"
    static let kMsgKiaNiroPlugI: String =
        "Kia Niro Plug-In Hybrid, Hyundai Elantra Hybrid Blue, Mazda MX-30, Toyota Corolla Hybrid "
    static let kLblRateApp: String = "Rate app"
    static let kLblYes: String = "yes"
    static let kLblNickJoseph: String = "Nick Joseph"
    static let kMsgLikeUsOnFace: String = "Like us on facebook"
    static let kUnableToFetch: String = "Unable to fetch data"
    static let kMsgOmgILeftMyU2: String = "Omg I left my umberella in your car"
    static let kLblDelivery: String = "Delivery"
    static let kLblBusiness: String = "Business"
    static let kMsgTLNlahdenkat2: String = "Töölönlahdenkatu 4, Helsinki "
    static let kMsgVaikeAmerika2: String =
        "Vaike Amerika 23, Tallinn            7.5€\n2 Oct, 2:45pm"
    static let kMsgAppAndFeature: String = "App and features"
    static let kLbl15: String = "                15€\n"
    static let kLblWorkEmail: String = "Work email"
    static let kMsgEnterYourMobi: String = "Enter your mobile number"
    static let kLbl12Oct510pm: String = "12 Oct, 5:10pm"
    static let kMsgGetHelpWithS: String = "Get help with something else"
    static let kLbl: String = ">"
    static let kLblSpecialNeeds: String = "Special needs"
    static let kMsgEcotaxiBalance: String =
        "ecoTaxi balance is not available with this \npayment method "
    static let kLbl1Min2: String = "1\nMin"
    static let kMsgHowCanWeHelp: String = "How can we help?"
    static let kLblMyTrips2: String = "My trips"
    static let kLbl0: String = "0€"
    static let kMsgYourPromotion: String = "Your promotion\nwill appear here"
    static let kLblCash: String = "Cash"
    static let kMsgPetFriendly1: String = "Pet friendly \n10€‎"
    static let kMsgChildFriendly: String = "Child friendly \n9€‎"
    static let kMsgComingInTwoM: String = "Coming in two minutes!"
    static let kLblTermsOfUse: String = "Terms of use"
    static let kMsgInboxViewOpen: String = "Inbox\nview open chats"
    static let kMsgWouldYouLike: String =
        "Would you like to try out Tesla to have an adorable experience?Have a ride in a great car at that time helping the planet!"
    static let kLbl10Oct640pm: String = "10 Oct, 6:40pm"
    static let kLblNataliJohnDoe: String = "Natali John Doe"
    static let kLbl0Min: String = "0\nmin"
    static let kMsgGetHelpWithA: String = "Get help with a recent ride"
    static let kMsgBecomeADriver: String = "Become a driver\nEarn money on your shedules"
    static let kLblAboutEcotaxi: String = "About ecoTaxi"
    static let kLbl59: String = "     5.9€\n"
    static let kMsgResolveConvers: String = "Resolve conversation?"
    static let kLblBecomeADriver: String = "Become a driver\n"
    static let kLblPromoCode: String = "Promo code"
    static let kMsgWhereAreWeGo: String = "Where are we going?"
    static let kLblOct2022: String = "Oct 2022"
    static let kMsgSeeTransaction: String = "See transactions"
    static let kLblAntonIvanovich: String = "Anton Ivanovich"
    static let kMsgIMWearingAB: String = "I’m wearing a black coat"
    static let kMsgGladIAmFive: String = "Glad I am five minutes away, will bring\nit to you now"
    static let kLblSettings: String = "Settings"
    static let kLblClickForMore: String = "click for more"
    static let kMsgOtakaari24Es2: String = "Otakaari 24, Espoo "
    static let kMsgCareersAtEcot: String = "Careers at ecoTaxi"
    static let kLblOrionintie: String = "Orionintie"
    static let kLbl2Oct245pm: String = "2 Oct, 2:45pm"
    static let kLblInbox: String = "Inbox\n"
    static let kMsgConversationsD: String = "conversations disappear after 48hours"
    static let kMsgByClickingOn: String =
        "by clicking on continue you are accepting\nour Terms of use"
    static let kMsgEnjoyRidesBei: String = "enjoy rides being sustainable"
    static let kMsgLeaveAComment: String = "Leave a comment for the driver"
}
